import os
import sqlite3

from dotenv import load_dotenv


# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================

load_dotenv()


# =========================================================
# DATABASE SETTINGS
# =========================================================

DATABASE_URL = os.getenv("DATABASE_URL")

DATABASE = "campus_market.db"


# =========================================================
# POSTGRESQL CONNECTION WRAPPER
# =========================================================

class PostgresConnection:

    def __init__(self, connection):
        self.connection = connection

    def execute(self, query, params=None):

        from psycopg2.extras import DictCursor

        # -------------------------------------------------
        # Convert SQLite placeholders to PostgreSQL
        # -------------------------------------------------

        query = query.replace("?", "%s")

        # -------------------------------------------------
        # Convert SQLite date arithmetic to PostgreSQL
        #
        # SQLite:
        # date('now', '-6 days')
        #
        # PostgreSQL:
        # CURRENT_DATE - 6
        # -------------------------------------------------

        query = query.replace(
            "date('now', '-6 days')",
            "CURRENT_DATE - 6"
        )

        # -------------------------------------------------
        # PostgreSQL cursor
        #
        # DictCursor supports both:
        #
        # row[0]
        # row["column_name"]
        # -------------------------------------------------

        cursor = self.connection.cursor(
            cursor_factory=DictCursor
        )

        if params is None:

            cursor.execute(query)

        else:

            cursor.execute(
                query,
                params
            )

        return cursor

    def executemany(
        self,
        query,
        params_list
    ):

        query = query.replace(
            "?",
            "%s"
        )

        query = query.replace(
            "date('now', '-6 days')",
            "CURRENT_DATE - 6"
        )

        cursor = self.connection.cursor()

        cursor.executemany(
            query,
            params_list
        )

        return cursor

    def commit(self):

        self.connection.commit()

    def rollback(self):

        self.connection.rollback()

    def close(self):

        self.connection.close()


# =========================================================
# GET DATABASE CONNECTION
# =========================================================

def get_db_connection():

    # =====================================================
    # RENDER / PRODUCTION
    # POSTGRESQL
    # =====================================================

    if DATABASE_URL:

        import psycopg2

        connection = psycopg2.connect(
            DATABASE_URL
        )

        return PostgresConnection(
            connection
        )


    # =====================================================
    # LOCAL DEVELOPMENT
    # SQLITE
    # =====================================================

    connection = sqlite3.connect(
        DATABASE
    )

    # Enable foreign keys.
    connection.execute(
        "PRAGMA foreign_keys = ON"
    )

    # Allow:

    # row["id"]

    # and:

    # row[0]

    connection.row_factory = sqlite3.Row

    return connection


# =========================================================
# CREATE DATABASE TABLES
# =========================================================

def create_tables():

    connection = get_db_connection()


    # =====================================================
    # POSTGRESQL
    # =====================================================

    if DATABASE_URL:

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (

                id INTEGER
                    GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                phone TEXT
                    NOT NULL
                    UNIQUE,

                password TEXT
                    NOT NULL,

                category TEXT
                    NOT NULL,

                created_at TIMESTAMP
                    DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS products (

                id INTEGER
                    GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                seller_id INTEGER
                    NOT NULL,

                name TEXT
                    NOT NULL,

                price TEXT
                    NOT NULL,

                category TEXT
                    NOT NULL,

                description TEXT
                    NOT NULL,

                location TEXT
                    NOT NULL,

                contact TEXT
                    NOT NULL,

                image TEXT,

                featured INTEGER
                    DEFAULT 0,

                sales_count INTEGER
                    DEFAULT 0,

                interest_count INTEGER
                    DEFAULT 0,

                created_at TIMESTAMP
                    DEFAULT CURRENT_TIMESTAMP,

                FOREIGN KEY (seller_id)
                    REFERENCES users(id)
                    ON DELETE CASCADE
            )
            """
        )


    # =====================================================
    # SQLITE
    # =====================================================

    else:

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (

                id INTEGER PRIMARY KEY AUTOINCREMENT,

                phone TEXT NOT NULL UNIQUE,

                password TEXT NOT NULL,

                category TEXT NOT NULL,

                created_at TIMESTAMP
                    DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS products (

                id INTEGER PRIMARY KEY AUTOINCREMENT,

                seller_id INTEGER NOT NULL,

                name TEXT NOT NULL,

                price TEXT NOT NULL,

                category TEXT NOT NULL,

                description TEXT NOT NULL,

                location TEXT NOT NULL,

                contact TEXT NOT NULL,

                image TEXT,

                featured INTEGER DEFAULT 0,

                sales_count INTEGER DEFAULT 0,

                interest_count INTEGER DEFAULT 0,

                created_at TIMESTAMP
                    DEFAULT CURRENT_TIMESTAMP,

                FOREIGN KEY (seller_id)
                    REFERENCES users(id)
                    ON DELETE CASCADE
            )
            """
        )


        # =================================================
        # SQLITE MIGRATION
        # =================================================

        existing_columns = connection.execute(
            "PRAGMA table_info(products)"
        ).fetchall()

        column_names = [
            column["name"]
            for column in existing_columns
        ]


        if "image" not in column_names:

            connection.execute(
                """
                ALTER TABLE products
                ADD COLUMN image TEXT
                """
            )


        if "featured" not in column_names:

            connection.execute(
                """
                ALTER TABLE products
                ADD COLUMN featured INTEGER
                DEFAULT 0
                """
            )


        if "sales_count" not in column_names:

            connection.execute(
                """
                ALTER TABLE products
                ADD COLUMN sales_count INTEGER
                DEFAULT 0
                """
            )


        if "interest_count" not in column_names:

            connection.execute(
                """
                ALTER TABLE products
                ADD COLUMN interest_count INTEGER
                DEFAULT 0
                """
            )


    # =====================================================
    # SAVE
    # =====================================================

    connection.commit()

    connection.close()