import os
import sqlite3

from dotenv import load_dotenv

load_dotenv()


DATABASE = "campus_market.db"


# =========================================================
# DATABASE CONNECTION
# =========================================================

def get_db_connection():

    database_url = os.getenv("DATABASE_URL")

    # -----------------------------------------------------
    # PRODUCTION: POSTGRESQL
    # -----------------------------------------------------

    if database_url:

        import psycopg2
        from psycopg2.extras import RealDictCursor

        class PostgresConnection:

            def __init__(self, url):
                self.connection = psycopg2.connect(
                    url,
                    cursor_factory=RealDictCursor
                )

            def execute(self, query, params=None):

                # Convert SQLite-style placeholders (?) to
                # PostgreSQL placeholders (%s).
                query = query.replace("?", "%s")

                cursor = self.connection.cursor()

                if params is None:
                    cursor.execute(query)
                else:
                    cursor.execute(query, params)

                return cursor

            def commit(self):
                self.connection.commit()

            def rollback(self):
                self.connection.rollback()

            def close(self):
                self.connection.close()

        return PostgresConnection(database_url)

    # -----------------------------------------------------
    # LOCAL DEVELOPMENT: SQLITE
    # -----------------------------------------------------

    connection = sqlite3.connect(DATABASE)

    connection.execute(
        "PRAGMA foreign_keys = ON"
    )

    connection.row_factory = sqlite3.Row

    return connection


# =========================================================
# CREATE TABLES
# =========================================================

def create_tables():

    database_url = os.getenv("DATABASE_URL")

    connection = get_db_connection()

    # =====================================================
    # POSTGRESQL
    # =====================================================

    if database_url:

        connection.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                phone TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                category TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        connection.execute("""
            CREATE TABLE IF NOT EXISTS products (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                seller_id INTEGER NOT NULL,
                name TEXT NOT NULL,
                price REAL NOT NULL,
                category TEXT NOT NULL,
                description TEXT NOT NULL,
                location TEXT NOT NULL,
                contact TEXT NOT NULL,
                image TEXT,
                featured INTEGER DEFAULT 0,
                sales_count INTEGER DEFAULT 0,
                interest_count INTEGER DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (seller_id)
                    REFERENCES users (id)
            )
        """)

        connection.commit()
        connection.close()

        return

    # =====================================================
    # SQLITE
    # =====================================================

    connection.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            phone TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            category TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            price REAL NOT NULL,
            category TEXT NOT NULL,
            description TEXT NOT NULL,
            location TEXT NOT NULL,
            contact TEXT NOT NULL,
            image TEXT,
            featured INTEGER DEFAULT 0,
            sales_count INTEGER DEFAULT 0,
            interest_count INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (seller_id)
                REFERENCES users (id)
        )
    """)

    # -----------------------------------------------------
    # SQLITE MIGRATIONS
    # -----------------------------------------------------

    columns = connection.execute(
        "PRAGMA table_info(products)"
    ).fetchall()

    column_names = [
        column["name"]
        for column in columns
    ]

    if "image" not in column_names:

        connection.execute(
            "ALTER TABLE products ADD COLUMN image TEXT"
        )

    if "featured" not in column_names:

        connection.execute(
            "ALTER TABLE products ADD COLUMN featured INTEGER DEFAULT 0"
        )

    if "sales_count" not in column_names:

        connection.execute(
            "ALTER TABLE products ADD COLUMN sales_count INTEGER DEFAULT 0"
        )

    if "interest_count" not in column_names:

        connection.execute(
            "ALTER TABLE products ADD COLUMN interest_count INTEGER DEFAULT 0"
        )

    connection.commit()

    connection.close()